(function(z){function A(){}function R(){return"avalon"+Math.random().toString(36).substring(2,15)+Math.random().toString(36).substring(2,15)}function H(a,b){for(var c in b)a[c]=b[c];return a}function ga(){if(C){for(var a=0,b;b=C[a++];)b();C=null}}function ha(a){return a.replace(/([a-z\d])([A-Z]+)/g,"$1-$2").toLowerCase()}function I(a){return 0>a.indexOf("-")&&0>a.indexOf("_")?a:a.replace(/[-_][^-_]/g,function(a){return a.charAt(1).toUpperCase()})}function ia(a){var b=!1;if(va.test(a)||+a+""===a)b=
!0;try{return b?eval("0,"+a):a}catch(c){return a}}function D(a,b,c){a="for(var "+a+"i=0,n = this.length;i < n;i++){"+b.replace("_","((i in this) && fn.call(scope,this[i],i,this))")+"}"+c;return Function("fn,scope",a)}function S(a,b,c){if(c){var d=a.length;c=b.length;d>c?a.splice(c,d-c):c>d&&a.push.apply(a,b.slice(d));c=Math.min(d,c);for(d=0;d<c;d++)a.set(d,b[d])}else for(d in b)b.hasOwnProperty(d)&&(a.hasOwnProperty(d)&&"$id"!==d)&&(a[d]=b[d])}function E(a){var b=a.$skipArray,c={},d={},e=[],f=[],
g=[],b=Array.isArray(b)?b:[];avalon.Array.ensure(b,"$skipArray","$watch","$unwatch","$fire","$events");J(a,function(a,h){if("function"===typeof h)g.push(a);else{if(-1!==b.indexOf(a)||"$"===a.charAt(0)&&!wa[a])return g.push(a);var l,m,n;h&&"object"===typeof h&&"function"===typeof h.get&&2>=Object.keys(h).length?(l=function(b){if(arguments.length)K||("function"===typeof h.set&&h.set.call(d,b),n!==b&&(n=b,L(l),d.$events&&d.$fire(a,b,m)));else return T&&ja(l),m=h.get.call(d)},f.push(function(){t[p]=this;
this();delete t[p]}.bind(l))):(e.push(a),l=function(b){if(arguments.length)!K&&n!==b&&(/Array|Object/.test(avalon.type(b))?m&&m.$id?S(m,b,Array.isArray(b)):m=Array.isArray(b)?ka(b):E(b):m=b,L(l),d.$events&&d.$fire(a,b,m));else return ja(l),m});l[y]=[];c[a]={set:l,get:l,enumerable:!0}}});M?M(d,c):d=xa(c,g);g.forEach(function(b){d[b]=a[b]});e.forEach(function(b){d[b]=a[b]});f.forEach(function(a){a()});d.$watch&&(d.$events={},d.$watch=U.$watch.bind(d),d.$unwatch=U.$unwatch.bind(d),d.$fire=U.$fire.bind(d));
d.$id=R();return d}function ja(a){t[p]&&(a=a[y])&&avalon.Array.ensure(a,t[p])}function L(a,b){var c=a[y];if(c&&c.length)for(var d=[].slice.call(arguments,1),e=c.concat(),f=0,g;g=e[f++];)(b=g.element)&&!b.noRemove&&(0===b.sourceIndex||null===b.parentNode)?(avalon.Array.remove(c,g),avalon.log(g+"")):g.apply(0,d)}function V(a,b){b=b||[];var c=a.getAttribute(u+"skip"),d=a.getAttribute(u+"important"),e=a.getAttribute(u+"controller");if("string"!==typeof c){if(d)if(avalon.models[d])b=[avalon.models[d]],
a.removeAttribute(u+"important");else return;else if(e){c=avalon.models[e];if(!c)return;b=[c].concat(b);a.removeAttribute(u+"controller")}for(var c=b,d=[],e=0,f;f=a.attributes[e++];)if(f.specified){var g=!1,k=!1;if(-1!==f.name.indexOf(u)){var h=f.name.replace(u,"");if(0<h.indexOf("-"))var l=h.split("-"),h=l.shift();k=!0;g="function"===typeof r[h]}g&&d.push({type:h,args:l||[],element:a,remove:k,node:f,value:f.nodeValue})}W(d,c);if(!1===a.canHaveChildren||!ya[a.tagName]){h=[];for(d=a.firstChild;d;d=
d.nextSibling)1===d.nodeType?V(d,b):3===d.nodeType&&h.push(d);for(l=0;d=h[l++];)c=b,d=la(d),d.length&&W(d,c)}}}function ma(a){var b=[];if(na(a)){do a=a.replace(za,function(a,d){d&&b.push({value:d,expr:!1});return""}),a=a.replace(Aa,function(a,d){if(d){var e=[];0<d.indexOf("|")&&(d=d.replace(/\|\s*(\w+)\s*(\([^)]+\))?/g,function(a,b,d){e.push(b+(d||""));return""}));b.push({value:d,expr:!0,filters:e.length?e:void 0})}return""});while(na(a));a&&b.push({value:a,expr:!1})}return b}function W(a,b){a.forEach(function(a){r[a.type](avalon.mix({},
a),b);a.remove&&a.element.removeAttribute(a.node.name)})}function la(a){var b=[],c=ma(a.nodeValue);if(c.length){for(;c.length;){var d=c.shift(),e=z.createTextNode(d.value);if(d.expr){var f=d.filters,d={type:"text",node:e,args:[],element:a.parentNode,value:d.value,filters:f};f&&-1!==f.indexOf("html")&&(avalon.Array.remove(f,"html"),d.type="html",d.replace=!0);b.push(d)}F.appendChild(e)}a.parentNode.replaceChild(F,a)}return b}function Ba(a,b,c,d,e,f){var g=!1;if(g=X?a instanceof ReferenceError:a instanceof
TypeError){a=window.opera?a.message.split("Undefined variable: ")[1]:a.message.replace("Can't find variable: ","").replace("\u201c","").replace("'","");a=(a.match(/^[\w$]+/)||[""])[0];for(var g=0,k;k=c[g++];)if(k.hasOwnProperty(a)){var h=k.$id+f;-1===d.indexOf(h)&&(d.push(h),e.push(k));c=RegExp("(^|[^\\w\\u00c0-\\uFFFF_])("+a.replace(Ca,"\\$1")+")($|[^\\w\\u00c0-\\uFFFF_])","g");return b.replace(c,function(a,b,d,c){return b+h+"."+d+c})}}}function Y(a,b,c){var d=[],e=[],f=new Date-0,g;if(Da){var k=
f+1,h=k+1,l=[],m=[],n=!0;a=a.replace(Ea,function(a){l.push(a);return k}).replace(Fa,function(a){m.push(a);return h});do try{var s=Function.apply(Function,d.concat("return "+a));g=s.apply(s,e);n=!1}catch(N){a=Ba(N,a,b,d,e,f),n="string"===typeof a}while(n);if(a)l.length&&(a=a.replace(RegExp(k,"g"),function(){return l.shift()})),m.length&&(a=a.replace(RegExp(h,"g"),function(){return m.shift()})),a="var ret"+f+" = "+a;else return c.compileFn=function(){return""},""}else{b.forEach(function(a){var b=a.$id+
""+f;-1===d.indexOf(b)&&(d.push(b),e.push(a))});a="var ret"+f+" = "+a+"\r\n";for(b=0;n=d[b++];)a="with("+n+"){\r\n"+a+"\r\n}\r\n"}if(c.filters){n=[];n.push(a,"\r\n");b=0;for(var q;q=c.filters[b++];){var p=q.indexOf("(");-1!==p?(a=q.slice(p+1,q.lastIndexOf(")")).trim(),a=","+a,q=q.slice(0,p).trim()):a="";n.push(" if(filters",f,".",q,"){\r\n\ttry{ret",f," = filters",f,".",q,"(ret",f,a,")}catch(e){};\r\n}\r\n")}a=n.join("");d.push("filters"+f);e.push(avalon.filters);delete c.filters}c.compileArgs=e;
try{s=Function.apply(Function,d.concat(a+("\r\nreturn ret"+f))),g=s.apply(s,e),c.compileFn=s}catch(r){c.remove=!1,c.compileFn=function(){return""},g=""}n=d=null;return g}function na(a){var b=a.indexOf("{{");return-1!==b&&b<a.indexOf("}}")}function v(a,b,c,d,e){var f,g;f=c.filters;var k=a.trim();if(!f&&!e){f=0;for(var h;h=b[f++];)if(h.hasOwnProperty(k)){g=h;break}}f=g?function(){d(g[k])}:function(){var f=c.compileFn;"function"===typeof f?f=f.apply(f,c.compileArgs||[]):e?(f=e.map(function(a){return a.expr?
Y(a.value,b,c):a.value}).join(""),delete c.compileFn):f=Y(a,b,c);d(f)};f.toString=function(){return"eval("+a+")"};f.element=c.element;t[p]=f;T=!0;f();T=!1;delete t[p]}function Ga(a){var b=a.target=a.srcElement;a.which=null!=a.charCode?a.charCode:a.keyCode;/mouse|click/.test(a.type)&&(b=b.ownerDocument||z,b="BackCompat"===b.compatMode?b.body:b.documentElement,a.pageX=a.clientX+(b.scrollLeft>>0)-(b.clientLeft>>0),a.pageY=a.clientY+(b.scrollTop>>0)-(b.clientTop>>0));a.preventDefault=function(){a.returnValue=
!1};a.stopPropagation=function(){a.cancelBubble=!0};return a}function oa(a){return Array.isArray(a)?a.$id?a:ka(a):"Object"===avalon.type(a)?a.$id?a:E(a):a}function ka(a){var b=a.map(oa);b.$id=R();b[y]=[];var c=E({length:a.length});"push,pop,shift,unshift,splice".replace(w,function(a){var e=[][a];b[a]=function(){var b=this.length,g=[].slice.call(arguments);/push|unshift|splice/.test(a)&&(g=g.map(oa));var k=e.apply(this,g);L(this,a,g,b);c.length=this.length;return k}});"sort,reverse".replace(w,function(a){var c=
[][a];b[a]=function(){var a=c.apply(this.concat(),arguments);a.forEach(function(a,b){this.set(b,a)},this);return a}});b.isCollection=!0;b.clear=function(){this.length=0;L(this,"clear",[]);c.length=0;return this};b.update=function(a){Array.isArray(a)&&S(this,a,!0);return this};b.sortBy=function(a,b){this.update(avalon.Array.sortBy(this.concat(),a,b));return this};b.contains=function(a){return-1!==this.indexOf(a)};b.ensure=function(a){this.contains(a)||this.push(a);return this};b.set=function(a,b){if(0<=
a&&a<this.length)if(/Array|Object/.test(avalon.type(b)))S(this[a],b,Array.isArray(b));else if(this[a]!==b){this[a]=b;for(var c=0,g;g=this[y][c++];)(g=g.$vms&&g.$vms[a])&&(g[g.$itemName]=b)}return this};b.size=function(){return c.length};b.remove=function(a){a=this.indexOf(a);return this.removeAt(a)};b.removeAt=function(a){if(0<=a&&0===a%1)return this.splice(a,1)[0]};b.removeAll=function(a){if(Array.isArray(a))a.forEach(function(a){b.remove(a)});else if("function"===typeof a)for(var c=this.length-
1;0<=c;c--)a(this[c],c)&&this.splice(c,1);else this.clear()};return b}function pa(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function Z(a,b){for(var c=a.firstChild;c;c=c.nextSibling)if(c.id===c.nodeValue+b)return c}function O(a,b,c){c=c||0;for(a=a.firstChild;a;a=a.nextSibling)8===a.nodeType&&a.nodeValue===b&&(a.id!==b+c&&(a.id=b+c,a.$scope.$index=c),c++)}function $(a,b){for(var c=[a],d=a.$view,e=a.nextSibling;e&&!(8===e.nodeType&&e.id===b);e=e.nextSibling)c.push(e);for(e=0;a=c[e++];)d.appendChild(a);
pa(d)}function qa(a,b,c,d,e){var f=d.scopes,g=d.element;b=Ha(a,b,c,d.args);f=[b].concat(f);e.splice(a,0,b);var k=d.view.cloneNode(!0);d=[];var h=[];for(e=k.firstChild;e;e=e.nextSibling)1===e.nodeType?h.push(e):3===e.nodeType?d.push(e):8===e.nodeType&&(e.id=e.nodeValue+a,e.$scope=b,e.$view=k.cloneNode(!1));g.insertBefore(k,c.place||null);for(a=0;e=h[a++];)V(e,f.concat());if(!g.inprocess){g.inprocess=1;var l=g.hidden;g.hidden=!0}for(a=0;e=d[a++];)c=f.concat(),b=la(e),b.length&&W(b,c);g.inprocess&&(g.hidden=
l,g.inprocess=0)}function Ha(a,b,c,d){d=d[0]||"$data";var e={};e.$index=a;e.$itemName=d;e[d]={get:function(){return b},set:function(a){b=a}};e.$first={get:function(){return 0===this.$index}};e.$last={get:function(){return this.$index===c.length-1}};e.$remove=function(){return c.remove(b)};return E(e)}var t={},ra={},C=[],p=new Date-0,y="$"+p,K=!1,T=!1,w=/[^, ]+/g,u="ms-",X=window.dispatchEvent,P=z.documentElement,Ia=Object.prototype.toString,aa=document.createElement("div"),F=z.createDocumentFragment(),
ba="propertyIsEnumerable isPrototypeOf hasOwnProperty toLocaleString toString valueOf constructor".split(" ");avalon=function(a){return new avalon.init(a)};avalon.init=function(a){this[0]=this.element=a};avalon.fn=avalon.prototype=avalon.init.prototype;H(avalon,{mix:H,rword:w,subscribers:y,ui:{},models:{},log:function(a){window.console&&console.log(a)},noop:A,error:function(a,b){throw new (b||Error)(a);},ready:function(a){"function"===typeof a&&(Array.isArray(C)?C.push(a):a())},type:function(a){return null===
a?"Null":void 0===a?"Undefined":Ia.call(a).slice(8,-1)},oneObject:function(a,b){"string"===typeof a&&(a=a.match(w)||[]);for(var c={},d=void 0!==b?b:1,e=0,f=a.length;e<f;e++)c[a[e]]=d;return c},range:function(a,b,c){c||(c=1);null==b&&(b=a||0,a=0);var d=-1;b=Math.max(0,Math.ceil((b-a)/c));for(var e=Array(b);++d<b;)e[d]=a,a+=c;return e},bind:X?function(a,b,c,d){a.addEventListener(b,c,!!d);return c}:function(a,b,c){function d(b){return c.call(a,Ga(b||window.event))}a.attachEvent&&a.attachEvent("on"+b,
d);return d},unbind:X?function(a,b,c,d){a.removeEventListener(b,c||A,!!d)}:function(a,b,c){a.detachEvent("on"+b,c||A)},forEach:function(a,b){if(a){var c=0;if(Array.isArray(a)||"Object"===avalon.type(a)&&!a.setTimeout&&isFinite(a.length)&&a[0])for(var d=a.length;c<d;c++)b(c,a[c]);else for(c in a)a.hasOwnProperty(c)&&b(c,a[c])}}});var J=avalon.forEach;avalon.bind(window,"load",ga);avalon.bind(window,"DOMContentLoaded",ga);var va=/^(?:null|false|true|NaN|\{.*\}|\[.*\])$/,Q=/\S+/g;H(avalon.fn,{hasClass:function(a){var b=
this[0]||{};if(1===b.nodeType)return!!b.className&&-1<(" "+b.className+" ").indexOf(" "+a+" ")},addClass:function(a){var b=this[0];if(a&&"string"===typeof a&&b&&1===b.nodeType)if(b.className){a=(b.className+" "+a).match(Q);a.sort();for(var c=a.length-1;0<c;--c)a[c]===a[c-1]&&a.splice(c,1);b.className=a.join(" ")}else b.className=a;return this},removeClass:function(a){var b=this[0];if(a&&"o"<typeof a&&b&&1===b.nodeType&&b.className){a=(a||"").match(Q)||[];for(var c=a.length,d=" "+b.className.match(Q).join(" ")+
" ",e=0;e<c;e++)d=d.replace(" "+a[e]+" "," ");b.className=d.slice(1,d.length-1)}return this},toggleClass:function(a,b){for(var c=b,d,e=0,f=a.match(Q)||[],g="boolean"===typeof b;d=f[e++];)c=g?c:!this.hasClass(d),this[c?"addClass":"removeClass"](d);return this},attr:function(a,b){return 2===arguments.length?(this[0].setAttribute(a,b),this):this[0].getAttribute(a)},data:function(a,b){a="data-"+ha(a||"");switch(arguments.length){case 2:return this.attr(a,b),this;case 1:var c=this.attr(a);return ia(c);
case 0:for(var c=this[0].attributes,d={},e=0,f;f=c[e++];)a=f.name,a.indexOf("data-")||(a=I(a.slice(5)),d[a]=ia(f.value));return d}},removeData:function(a){a="data-"+ha(a);this[0].removeAttribute(a);return this},css:function(a,b){var c=this[0];if(c&&c.style){var d=/\_/.test(a)?I(a):a,e;a:{var f=e=void 0;if(ca[d])e=ca[d];else{e=e||P.style;for(var g=0,k=sa.length;g<k;g++)if(f=I(sa[g]+d),f in e){e=ca[d]=f;break a}e=null}}a=e||d;if(1===arguments.length)return d=x[d+":get"]||x["@:get"],d(c,a);e=typeof b;
if("number"!==e||isFinite(b+""))return"number"===e&&!Ja[d]&&(b+="px"),d=x[d+":set"]||x["@:set"],d(c,a,b),this}},bind:function(a,b,c){if(this[0])return avalon.bind(this[0],a,b,c)},unbind:function(a,b,c){this[0]&&avalon.unbind(this[0],a,b,c);return this},val:function(a){var b=this[0];if(b&&1===b.nodeType){var c=0===arguments.length,d=c?":get":":set",e=da,f;f=b.tagName.toLowerCase();f="input"===f&&/checkbox|radio/.test(b.type)?"checked":f;if(d=e[f+d])var g=d(b,a);else{if(c)return(b.value||"").replace(/\r/g,
"");b.value=a}}return c?g:this}});var x=avalon.cssHooks={},sa=["","-webkit-","-o-","-moz-","-ms-"],ca={"float":"cssFloat"in P.style?"cssFloat":"styleFloat",background:"backgroundColor"},Ja=avalon.oneObject("columnCount,fillOpacity,fontWeight,lineHeight,opacity,orphans,widows,zIndex,zoom");x["@:set"]=function(a,b,c){a.style[b]=c};if(window.getComputedStyle)x["@:get"]=function(a,b){var c,d=window.getComputedStyle(a,null);d&&(c="filter"===b?d.getPropertyValue(b):d[b],""===c&&(c=a.style[b]));return c};
else{var Ka=/^-?(?:\d*\.)?\d+(?!px)[^\d\s]+$/i,La=/^(top|right|bottom|left)$/,ea=!!window.XDomainRequest,Ma={thin:ea?"1px":"2px",medium:ea?"3px":"4px",thick:ea?"5px":"6px"};x["@:get"]=function(a,b){var c=a.currentStyle,d=c[b];if(Ka.test(d)&&!La.test(d)){var e=a.style,f=e.left,g=a.runtimeStyle.left;a.runtimeStyle.left=c.left;e.left="fontSize"===b?"1em":d||0;d=e.pixelLeft+"px";e.left=f;a.runtimeStyle.left=g}"medium"===d&&(b=b.replace("Width","Style"),"none"===c[b]&&(d="0px"));return""===d?"auto":Ma[d]||
d};x["opacity:set"]=function(a,b){a.style.filter="alpha(opacity="+100*b+")";a.style.zoom=1};x["opacity:get"]=function(a){a=a.filters.alpha||a.filters["DXImageTransform.Microsoft.Alpha"];return(a?a.opacity:100)/100+""}}"Width,Height".replace(w,function(a){var b=a.toLowerCase(),c="client"+a,d="scroll"+a,e="offset"+a;avalon.fn[b]=function(f){var g=this[0];if(0===arguments.length){if(g.setTimeout)return g["inner"+a]||g.document.documentElement[c];if(9===g.nodeType){var k=g.documentElement;return Math.max(g.body[d],
k[d],g.body[e],k[e],k[c])}return parseFloat(this.css(b))||0}return this.css(b,f)}});avalon.fn.offset=function(){var a=this[0],b=a&&a.ownerDocument,c={left:0,top:0};if(!b)return c;var a=a.getBoundingClientRect(),d=b.defaultView||b.parentWindow,b=navigator.vendor||"BackCompat"===b.compatMode?b.body:b.documentElement,e=b.clientLeft>>0,f=d.pageXOffset||b.scrollLeft;c.top=a.top+(d.pageYOffset||b.scrollTop)-(b.clientTop>>0);c.left=a.left+f-e;return c};var da={"option:get":function(a){var b=a.attributes.value;
return!b||b.specified?a.value:a.text},"select:get":function(a,b){for(var c,d=a.options,e=a.selectedIndex,f=da["option:get"],g="select-one"===a.type||0>e,k=g?null:[],h=g?e+1:d.length,l=0>e?h:g?e:0;l<h;l++)if(c=d[l],(c.selected||l===e)&&!c.disabled){b=f(c);if(g)return b;k.push(b)}return k},"select:set":function(a,b){b=[].concat(b);for(var c=da["option:get"],d=0,e;e=a.options[d++];)e.selected=!!~b.indexOf(c(e));b.length||(a.selectedIndex=-1)}};"\u53f8\u5f92\u6b63\u7f8e".trim||(String.prototype.trim=
function(){return this.replace(/^[\s\xA0]+/,"").replace(/[\s\xA0]+$/,"")});for(var Oa in{toString:1})ba=!1;Object.keys||(Object.keys=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);if(ba&&a)for(var d=0;c=ba[d++];)a.hasOwnProperty(c)&&b.push(c);return b});Array.isArray||(Array.isArray=function(a){return"Array"===avalon.type(a)});Function.prototype.bind||(Function.prototype.bind=function(a){if(2>arguments.length&&void 0===a)return this;var b=this,c=arguments;return function(){var d=
[],e;for(e=1;e<c.length;e++)d.push(c[e]);for(e=0;e<arguments.length;e++)d.push(arguments[e]);return b.apply(a,d)}});H(Array.prototype,{indexOf:function(a,b){var c=this.length,d=~~b;for(0>d&&(d+=c);d<c;d++)if(this[d]===a)return d;return-1},lastIndexOf:function(a,b){var c=this.length,d=null==b?c-1:b;for(0>d&&(d=Math.max(0,c+d));0<=d;d--)if(this[d]===a)return d;return-1},forEach:D("","_",""),filter:D("r=[],j=0,","if(_)r[j++]=this[i]","return r"),map:D("r=[],","r[i]=_","return r"),some:D("","if(_)return true",
"return false"),every:D("","if(!_)return false","return true")});avalon.Array={sortBy:function(a,b,c){a=a.map(function(a,e){return{el:a,re:b.call(c,a,e)}}).sort(function(a,b){var c=a.re,g=b.re;return c<g?-1:c>g?1:0});return avalon.Array.pluck(a,"el")},pluck:function(a,b){return a.filter(function(a){return null!=a[b]})},ensure:function(a){[].slice.call(arguments,1).forEach(function(b){~a.indexOf(b)||a.push(b)});return a},removeAt:function(a,b){return!!a.splice(b,1).length},remove:function(a,b){var c=
a.indexOf(b);return~c?avalon.Array.removeAt(a,c):!1}};var G;"function"===typeof setImmediate?G=setImmediate.bind(window):function(){function a(){--e;if(++g>=d){g=0;d*=4;for(var a=f&&Math.min(f-1,d);e<a;)++e,k()}for(;f;)--f,b=b.next,a=b.task,b.task=void 0,a();g=0}var b={task:void 0,next:null},c=b,d=2,e=0,f=0,g=0,k=void 0;G=function(a){c=c.next={task:a,next:null};e<++f&&e<d&&(++e,k())};if("undefined"!==typeof MessageChannel){var h=new MessageChannel;h.port1.onmessage=a;k=function(){h.port2.postMessage(0)}}else k=
function(){setTimeout(a,0)}}();avalon.nextTick=G;avalon.define=function(a,b,c){var d=[].slice.call(arguments);"string"!==typeof a&&(a=!avalon.models.root?"root":R(),d.unshift(a));Array.isArray(d[1])||d.splice(1,0,[]);b=d[1];"function"!==typeof d[2]&&avalon.error("factory\u5fc5\u987b\u662f\u51fd\u6570");c=d[2];d={$events:{},$watch:A,$unwatch:A,$fire:A};b.unshift(d);c(d);d=E(d);K=!0;b[0]=d;c.apply(0,b);b.shift();K=!1;d.$id=a;return avalon.models[a]=d};var U={$watch:function(a,b){var c=this.$events[a];
c?c.push(b):this.$events[a]=[b];return this},$unwatch:function(a,b){var c=arguments.length;if(0===c)this.$events={};else if(1===c)this.$events[a]=[];else for(var c=this.$events[a]||[],d=c.length;-1<--d;)if(c[d]===b)return c.splice(d,1);return this},$fire:function(a){for(var b=this.$events[a]||[],c=this.$events.$all||[],d=[].slice.call(arguments,1),e=0,f;f=b[e++];)f.apply(this,d);for(e=0;f=c[e++];)f.apply(this,d)}},wa=avalon.oneObject("$index,$remove,$first,$last"),fa=Object.defineProperty;try{fa({},
"_",{value:"x"});var M=Object.defineProperties}catch(Pa){"__defineGetter__"in avalon&&(fa=function(a,b,c){"value"in c&&(a[b]=c.value);"get"in c&&a.__defineGetter__(b,c.get);"set"in c&&a.__defineSetter__(b,c.set);return a},M=function(a,b){for(var c in b)b.hasOwnProperty(c)&&fa(a,c,b[c]);return a})}if(!M&&window.VBArray){window.execScript("Function parseVB(code)\n\tExecuteGlobal(code)\nEnd Function","VBScript");var Na=function(a,b,c){var d=a[b]&&a[b].set;if(3===arguments.length)d(c);else return d()},
xa=function(a,b){b=b.concat();avalon.Array.ensure(b,"hasOwnProperty");avalon.Array.ensure(b,"$id");var c="VBClass"+setTimeout("1"),d={},e=[];e.push("Class "+c,"\tPrivate [__data__], [__proxy__]","\tPublic Default Function [__const__](d, p)","\t\tSet [__data__] = d: set [__proxy__] = p","\t\tSet [__const__] = Me","\tEnd Function");b.forEach(function(a){d[a]=!0;e.push("\tPublic ["+a+"]")});Object.keys(a).forEach(function(a){d[a]=!0;e.push("\tPublic Property Let ["+a+"](val)",'\t\tCall [__proxy__]([__data__], "'+
a+'", val)',"\tEnd Property","\tPublic Property Set ["+a+"](val)",'\t\tCall [__proxy__]([__data__], "'+a+'", val)',"\tEnd Property","\tPublic Property Get ["+a+"]","\tOn Error Resume Next","\t\tSet["+a+'] = [__proxy__]([__data__],"'+a+'")',"\tIf Err.Number <> 0 Then","\t\t["+a+'] = [__proxy__]([__data__],"'+a+'")',"\tEnd If","\tOn Error Goto 0","\tEnd Property")});e.push("End Class");e.push("Function "+c+"Factory(a, b)","\tDim o","\tSet o = (New "+c+")(a, b)","\tSet "+c+"Factory = o","End Function");
window.parseVB(e.join("\r\n"));c=window[c+"Factory"](a,Na);c.hasOwnProperty=function(a){return!0===d[a]};return c}}avalon.scan=function(a,b){a=a||P;V(a,b?[b]:[])};var ya=avalon.oneObject("area,base,basefont,br,col,hr,img,input,link,meta,param,embed,wbr,script,style,textarea"),Ca=/([-.*+?^${}()|[\]\/\\])/g,Da=function(){return!this}(),Fa=/"([^\\"\n]|\\.)*"/g,Ea=/'([^\\'\n]|\\.)*'/g,za=/([^{]*)\{\{/,Aa=/([^}]*)\}\}/;"contentEditable,isMap,longDesc,noHref,noResize,noShade,readOnly,useMap".replace(w,
function(a){ra[a.toLowerCase()]=a});var r=avalon.bindingHandlers={"if":function(a,b){var c=a.element,d=c.ownerDocument.createComment("@"),e=c.parentNode;v(a.value,b,a,function(a){G(function(){if(a){if(!c.parentNode||11===c.parentNode.nodeType)e.replaceChild(c,d),c.noRemove=0}else c.parentNode&&1===c.parentNode.nodeType&&(e.replaceChild(d,c),c.noRemove=1)})})},on:function(a,b){var c=a.element;v(a.value,b,a,function(d){var e=a.args[0];e&&"function"===typeof d&&(c.$scopes||(c.$scope=b[0],c.$scopes=b),
avalon.bind(c,e,d))})},text:function(a,b){var c=a.node;v(a.value,b,a,function(a){c.nodeValue=a})},visible:function(a,b){var c=a.element;v(a.value,b,a,function(a){c.style.display=a?"block":"none"})},href:function(a,b){var c=a.value.trim(),d=!0,e=a.type,f=avalon(a.element);-1<c.indexOf("{{")&&2<c.indexOf("}}")&&(d=!1,/^\{\{([^}]+)\}\}$/.test(c)&&(d=!0,c=RegExp.$1));v(c,b,a,function(b){"css"===e?f.css(a.args[0],b):a.element[e]=b},d?null:ma(a.value))},disabled:function(a,b){var c=a.element,d=a.type,e=
ra[d]||d;v(a.value,b,a,function(a){c[e]=!!a})},"class":function(a,b){var c=a.element,d=avalon(c);v(a.value,b,a,function(e){if(a.args){var f=a.args.join("-");"function"===typeof e&&(c.$scopes||(c.$scope=b[0],c.$scopes=b),e=e.call(c));d.toggleClass(f,!!e)}else"string"===typeof e?e.replace(w,function(a){d.addClass(a)}):e&&"object"===typeof e&&J(e,function(a,b){d.toggleClass(a,!!b)})})},hover:function(a){var b=avalon(a.element);b.bind("mouseenter",function(){b.addClass(a.value)});b.bind("mouseleave",
function(){b.removeClass(a.value)})},html:function(a,b){var c=a.element;v(a.value,b,a,function(b){b=null==b?"":b+"";if(a.replace){for(aa.innerHTML=b;aa.firstChild;)F.appendChild(aa.firstChild);c.replaceChild(F,a.node)}else c.innerHTML=b})},ui:function(a,b,c){var d=a.value.trim();if("function"===typeof avalon.ui[d]){var e=(avalon(a.element).data("id")||"").trim(),e=e||d+setTimeout("1");a.element.setAttribute(u+"controller",e);var f=a.args[0];if(f){for(var g=0,k;k=b[g++];)if(k.hasOwnProperty(f)){c=
k[f];break}if(!c)for(g in avalon.models)if(k=avalon.models[g],k.hasOwnProperty(f)){c=k[f];break}}avalon.ui[d](a.element,e,c)}},options:function(a,b){var c=a.element;for("SELECT"!==c.tagName&&avalon.error("options\u7ed1\u5b9a\u53ea\u80fd\u7ed1\u5728SELECT\u5143\u7d20");0<c.length;)c.remove(0);var d=a.args[0];v(a.value,b,a,function(e){Array.isArray(e)?G(function(){c.setAttribute(u+"each-option",a.value);var f=new Option("{{option}}","");f.setAttribute("ms-value","option");c.options[0]=f;avalon.scan(c);
if(isFinite(d)&&(f=c.options[d]))f.selected=!0;f=b[0];if(d&&Array.isArray(f[d])){var g=avalon(c);g.val(f[d]);g.bind("change",function(){var a=g.val();e.clear();e.push.apply(e,a)})}}):avalon.error("options\u7ed1\u5b9a\u5fc5\u987b\u5bf9\u5e94\u4e00\u4e2a\u5b57\u7b26\u4e32\u6570\u7ec4")})}},B=r.model=function(a,b){var c=a.element,d=c.tagName;if("function"===typeof B[d]){var e=a.node.value,f;b.forEach(function(a){!f&&a.hasOwnProperty(e)&&(f=a)});f=f||{};B[d](c,f,e)}};B.INPUT=function(a,b,c){void 0===
a.name&&(a.name=c);var d=a.type,e=function(){b[c]=a.value},f=function(){var d=b[c];d!==a.value&&(a.value=void 0===d?"":d)};/^(password|textarea|text)$/.test(d)?(d=a.attributes[u+"event"]||{},d=d.value,"change"===d?avalon.bind(a,d,e):(window.addEventListener?a.addEventListener("input",e,!1):a.attachEvent("onpropertychange",e),9<=z.documentMode&&(a.attachEvent("onkeydown",function(a){a=a.keyCode;(8===a||46===a)&&e()}),a.attachEvent("oncut",e)))):"radio"===d?(f=function(){a.checked=b[c]===a.value},e=
function(){var d=!a.beforeChecked;b[c]=d;a.beforeChecked=a.checked=d},d=function(){a.beforeChecked=a.checked},null===a.onbeforeactivate?avalon.bind(a,"beforeactivate",d):avalon.bind(a,"mouseover",d),avalon.bind(a,"click",e)):"checkbox"===d&&(e=function(){a.checked?avalon.Array.ensure(b[c],a.value):avalon.Array.remove(b[c],a.value)},f=function(){var d=[].concat(b[c]);a.checked=0<=d.indexOf(a.value)},avalon.bind(a,"click",e));t[p]=f;f.element=a;f();delete t[p]};B.SELECT=function(a,b,c){function d(){var a=
b[c];a+""!==f&&(e.val(a),f=a+"")}var e=avalon(a),f=b[c]+"";e.bind("change",function(){var a=e.val();a+""!==f&&(b[c]=a,f=a+"")});t[p]=d;d.element=a;d();delete t[p]};B.TEXTAREA=B.INPUT;"autofocus,autoplay,async,checked,controls,declare,contenteditable,loop,multiple,noresize,readonly,selected".replace(w,function(a){r[a]=r.disabled});r.enabled=function(a,b){var c=a.element;v(a.value,b,a,function(a){c.disabled=!a})};"title,alt,src,value,css".replace(w,function(a){r[a]=r.href});"dblclick,mouseout,click,mouseover,mouseenter,mouseleave,mousemove,mousedown,mouseup,keypress,keydown,keyup,blur,focus,change".replace(w,
function(a){r[a]=function(b){b.args=[a];r.on.apply(0,arguments)}});if(!("onmouseenter"in P)){var ta=avalon.bind,ua={mouseenter:"mouseover",mouseleave:"mouseout"};avalon.bind=function(a,b,c){return ua[b]?ta(a,ua[b],function(d){var e=d.relatedTarget;if(!e||e!==a&&!(a.compareDocumentPosition(e)&16))delete d.type,d.type=b,c.call(a,d)}):ta(a,b,c)}}r.each=function(a,b){function c(b,e,g){var m=f.$id,n=c.$vms;switch(b){case "push":J(e,function(b,c){qa(g+b,c,f,a,n)});break;case "unshift":O(d,m,f.length-g);
f.place=d.firstChild;J(e,function(b,c){qa(b,c,f,a,n)});f.place=null;break;case "pop":if(e=Z(d,g-1))$(e,m+g),n.pop();break;case "shift":$(d.firstChild,m+1);O(d,m);n.shift();break;case "splice":b=e[0];var s=e[1],N=[].slice.call(e,2),q=0<=s?s:g-b;if(q&&(e=Z(d,b)))n.splice(b,q),$(e,m+(b+s)),O(d,m);N.length&&(f.place=Z(d,b),c("push",N,b),O(d,m),f.place=null);break;case "clear":n.length=0,pa(d)}}var d=a.element,e=a.value,f=1===b.length&&-1===e.indexOf(".")?b[0][e]:Y(e,b,a),e=F.cloneNode(!1),g=z.createComment(f.$id);
for(e.appendChild(g);d.firstChild;)e.appendChild(d.firstChild);a.view=e;a.scopes=b;c.$vms=[];(f||{}).isCollection&&f[y].push(c);c("push",f,0)};avalon.filters={uppercase:function(a){return a.toUpperCase()},html:function(a){return a},lowercase:function(a){return a.toLowerCase()},truncate:function(a,b,c){b=b||30;c=void 0===c?"...":c;return a.length>b?a.slice(0,b-c.length)+c:String(a)},camelize:I,escape:function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,
"&quot;").replace(/'/g,"&#39;")},currency:function(a,b){return(b||"\uffe5")+avalon.filters.number(a)},number:function(a,b,c,d){a=(a+"").replace(/[^0-9+\-Ee.]/g,"");a=!isFinite(+a)?0:+a;b=!isFinite(+b)?0:Math.abs(b);d=d||",";c=c||".";var e="",e=function(a,b){var c=Math.pow(10,b);return""+Math.round(a*c)/c},e=(b?e(a,b):""+Math.round(a)).split(".");3<e[0].length&&(e[0]=e[0].replace(/\B(?=(?:\d{3})+(?!\d))/g,d));if((e[1]||"").length<b)e[1]=e[1]||"",e[1]+=Array(b-e[1].length+1).join("0");return e.join(c)}};
avalon.filters.date=function(a){function b(a,b,c){var d="";0>a&&(d="-",a=-a);for(a=""+a;a.length<b;)a="0"+a;c&&(a=a.substr(a.length-b));return d+a}function c(a,c,d,e){return function(f){f=f["get"+a]();if(0<d||f>-d)f+=d;0===f&&-12===d&&(f=12);return b(f,c,e)}}function d(a,b){return function(c,d){var e=c["get"+a](),f=(b?"SHORT"+a:a).toUpperCase();return d[f][e]}}function e(a){var b;if(b=a.match(h)){a=new Date(0);var c=0,d=0,e=b[8]?a.setUTCFullYear:a.setFullYear,f=b[8]?a.setUTCHours:a.setHours;b[9]&&
(c=parseInt(b[9]+b[10],10),d=parseInt(b[9]+b[11],10));e.call(a,parseInt(b[1],10),parseInt(b[2],10)-1,parseInt(b[3],10));f.call(a,parseInt(b[4]||0,10)-c,parseInt(b[5]||0,10)-d,parseInt(b[6]||0,10),parseInt(b[7]||0,10))}return a}var f={yyyy:c("FullYear",4),yy:c("FullYear",2,0,!0),y:c("FullYear",1),MMMM:d("Month"),MMM:d("Month",!0),MM:c("Month",2,1),M:c("Month",1,1),dd:c("Date",2),d:c("Date",1),HH:c("Hours",2),H:c("Hours",1),hh:c("Hours",2,-12),h:c("Hours",1,-12),mm:c("Minutes",2),m:c("Minutes",1),ss:c("Seconds",
2),s:c("Seconds",1),sss:c("Milliseconds",3),EEEE:d("Day"),EEE:d("Day",!0),a:function(a,b){return 12>a.getHours()?b.AMPMS[0]:b.AMPMS[1]},Z:function(a){a=-1*a.getTimezoneOffset();return a=(0<=a?"+":"")+(b(Math[0<a?"floor":"ceil"](a/60),2)+b(Math.abs(a%60),2))}},g=/((?:[^yMdHhmsaZE']+)|(?:'(?:[^']|'')*')|(?:E+|y+|M+|d+|H+|h+|m+|s+|a|Z))(.*)/,k=/^\d+$/,h=/^(\d{4})-?(\d\d)-?(\d\d)(?:T(\d\d)(?::?(\d\d)(?::?(\d\d)(?:\.(\d+))?)?)?(Z|([+-])(\d\d):?(\d\d))?)?$/;return function(b,c){var d="",h=[],p,q;c=c||"mediumDate";
c=a[c]||c;"string"===typeof b&&(b=k.test(b)?parseInt(b,10):e(b));"Number"===avalon.type(b)&&(b=new Date(b));if("Date"===avalon.type(b)){for(;c;)(q=g.exec(c))?(h=h.concat(q.slice(1)),c=h.pop()):(h.push(c),c=null);h.forEach(function(c){p=f[c];d+=p?p(b,a):c.replace(/(^'|'$)/g,"").replace(/''/g,"'")});return d}}}({AMPMS:{"0":"\u4e0a\u5348",1:"\u4e0b\u5348"},DAY:{"0":"\u661f\u671f\u65e5",1:"\u661f\u671f\u4e00",2:"\u661f\u671f\u4e8c",3:"\u661f\u671f\u4e09",4:"\u661f\u671f\u56db",5:"\u661f\u671f\u4e94",
6:"\u661f\u671f\u516d"},MONTH:{"0":"1\u6708",1:"2\u6708",2:"3\u6708",3:"4\u6708",4:"5\u6708",5:"6\u6708",6:"7\u6708",7:"8\u6708",8:"9\u6708",9:"10\u6708",10:"11\u6708",11:"12\u6708"},SHORTDAY:{"0":"\u5468\u65e5",1:"\u5468\u4e00",2:"\u5468\u4e8c",3:"\u5468\u4e09",4:"\u5468\u56db",5:"\u5468\u4e94",6:"\u5468\u516d"},SHORTMONTH:{"0":"1\u6708",1:"2\u6708",2:"3\u6708",3:"4\u6708",4:"5\u6708",5:"6\u6708",6:"7\u6708",7:"8\u6708",8:"9\u6708",9:"10\u6708",10:"11\u6708",11:"12\u6708"},fullDate:"y\u5e74M\u6708d\u65e5EEEE",
longDate:"y\u5e74M\u6708d\u65e5",medium:"yyyy-M-d ah:mm:ss",mediumDate:"yyyy-M-d",mediumTime:"ah:mm:ss","short":"yy-M-d ah:mm",shortDate:"yy-M-d",shortTime:"ah:mm"});avalon.ready(function(){avalon.scan(document.body)})})(document);
